# ════════════════════════════════════════════════════════════════
# Global Configuration
# ════════════════════════════════════════════════════════════════
global:
  N_threads: 8

# ════════════════════════════════════════════════════════════════════
# Data Configuration
# ════════════════════════════════════════════════════════════════════
data:
  # ── data_path ──
  data_paths: default_global_setup

  # ── clean_data_options ──
  dict_clean_data_options: default_global_setup

  # ── Train/val/test splits ──
  dict_split_data_options: default_global_setup

  # ── Input/output keys ──
  features_labels_options:
    define_dataset_loaders_keys: [DESI_only, JPAS_matched]
    keys_xx: [OBS, MORPHTYPE_int]
    keys_yy: [SPECTYPE_int]
    normalize: true
    normalization_source_key: DESI_only
    key_survey_training: JPAS_matched

# ════════════════════════════════════════════════════════════════════
# Model Architecture
# ════════════════════════════════════════════════════════════════════
models:
  path_load: wandb_no_DA/my-sweep-0

# ════════════════════════════════════════════════════════════════════
# Training Configuration
# ════════════════════════════════════════════════════════════════════
training:
  path_save: default_global_setup
  default_overwrite : False

  sampling_strategy: true_random
  freeze_downstream_model: True
  
  NN_epochs: 2048
  # NN_batches_per_epoch: 8192
  # batch_size: 2048
  batch_size_val: null

  # lr: 0.01
  # weight_decay: 0.0001
  # clip_grad_norm: 100.0

  seed_mode: random
  seed: 0

  device: cuda
