# ════════════════════════════════════════════════════════════════
# Global Configuration
# ════════════════════════════════════════════════════════════════
global:
  N_threads: 8

# ════════════════════════════════════════════════════════════════════
# Data Configuration
# ════════════════════════════════════════════════════════════════════
data:
  # ── data_path ──
  data_paths: default_global_setup

  # ── clean_data_options ──
  dict_clean_data_options:
    apply_masks         : [unreliable, jpas_ignasi_dense, magic_numbers, negative_errors, nan_values, apply_additional_filters]
    mask_indices        : [0, -2]
    magic_numbers       : [-99, 99]
    i_band_sn_threshold : 0
    magnitude_flux_key  : DESI_FLUX_R
    magnitude_threshold : 22.5
    z_lim_QSO_cut       : 2.1
    manually_select_one_SPECTYPE_vs_rest : QSO_high

  # ── Train/val/test splits ──
  dict_split_data_options: default_global_setup

  # ── Input/output keys ──
  features_labels_options:
    define_dataset_loaders_keys: [DESI_only]
    keys_xx: [OBS, MORPHTYPE_int]
    keys_yy: [SPECTYPE_int]
    normalize: true
    normalization_source_key: DESI_only
    key_survey_training: DESI_only

# ════════════════════════════════════════════════════════════════════
# Model Architecture
# ════════════════════════════════════════════════════════════════════
models:
  path_load: null

# ════════════════════════════════════════════════════════════════════
# Training Configuration
# ════════════════════════════════════════════════════════════════════
training:
  path_save: default_global_setup
  default_overwrite : False

  sampling_strategy: true_random
  freeze_downstream_model: false
  
  NN_epochs: 512
  # NN_batches_per_epoch: 8192
  # batch_size: 5000
  batch_size_val: null

  # lr: 0.01
  # weight_decay: 0.0001
  # clip_grad_norm: 100.0

  seed_mode: deterministic
  # seed: 0

  device: cuda

# ════════════════════════════════════════════════════════════════
# Model Options
# ════════════════════════════════════════════════════════════════

encoders:
  # two-layer small encoder with light dropout
  - hidden_layers: [64, 32]
    dropout_rates: [0.01, 0.01, 0.01]

  # two-layer small encoder with heavy dropout
  - hidden_layers: [64, 32]
    dropout_rates: [0.3, 0.3, 0.3]

  # two-layer big encoder with light dropout
  - hidden_layers: [256, 128]
    dropout_rates: [0.01, 0.01, 0.01]

  # two-layer big encoder with heavy dropout
  - hidden_layers: [256, 128]
    dropout_rates: [0.3, 0.3, 0.3]

  # Three-layer small encoder with light dropout
  - hidden_layers: [128, 64, 32]
    dropout_rates: [0.01, 0.01, 0.01]

  # Three-layer small encoder with heavy dropout
  - hidden_layers: [128, 64, 32]
    dropout_rates: [0.3, 0.3, 0.3]

  # Three-layer encoder with light dropout
  - hidden_layers: [256, 128, 64]
    dropout_rates: [0.01, 0.01, 0.01]

  # Three-layer encoder with heavy dropout
  - hidden_layers: [256, 128, 64]
    dropout_rates: [0.3, 0.3, 0.3]

  # Narrow deep encoder, compressive
  - hidden_layers: [128, 64, 32, 16]
    dropout_rates: [0.0, 0.1, 0.2, 0.3]

  # Moderate width, 3-layer
  - hidden_layers: [256, 128, 64]
    dropout_rates: [0.1, 0.2, 0.2]

  # Uniform medium-depth encoder
  - hidden_layers: [128, 128, 128]
    dropout_rates: [0.1, 0.1, 0.1]

  # Deeper, consistent dropout, moderate width
  - hidden_layers: [128, 64, 64, 32]
    dropout_rates: [0.1, 0.1, 0.1, 0.1]

  # Same-width 4-layer encoder
  - hidden_layers: [64, 64, 64, 64]
    dropout_rates: [0.1, 0.1, 0.1, 0.1]

  # Compressing 5-layer encoder
  - hidden_layers: [256, 128, 64, 32, 16]
    dropout_rates: [0.2, 0.2, 0.2, 0.2, 0.2]

  # Middle-range capacity with alternating dropout
  - hidden_layers: [512, 128, 32]
    dropout_rates: [0.2, 0.1, 0.0]

  # Shallow wide encoder with regularization
  - hidden_layers: [512, 128]
    dropout_rates: [0.3, 0.3]


downstreams:
  # Minimal head
  - hidden_layers: [32]
    dropout_rates: [0.0]

  # Small 1-layer
  - hidden_layers: [64]
    dropout_rates: [0.1]

  # Two-layer compact head
  - hidden_layers: [128, 64]
    dropout_rates: [0.1, 0.1]

  # Two equal layers
  - hidden_layers: [128, 128]
    dropout_rates: [0.0, 0.0]

  # Three-layer narrow head
  - hidden_layers: [64, 32, 16]
    dropout_rates: [0.0, 0.1, 0.2]

  # Medium 3-layer with uniform dropout
  - hidden_layers: [128, 64, 32]
    dropout_rates: [0.1, 0.1, 0.1]

  # Narrow consistent dropout
  - hidden_layers: [64, 64]
    dropout_rates: [0.2, 0.2]

  # Mildly regularized decreasing width
  - hidden_layers: [128, 64, 32]
    dropout_rates: [0.3, 0.2, 0.1]

  # Compact deep
  - hidden_layers: [64, 64, 64, 64]
    dropout_rates: [0.1, 0.1, 0.1, 0.1]

  # Classic deep compression head
  - hidden_layers: [256, 128, 64, 32]
    dropout_rates: [0.2, 0.2, 0.2, 0.2]

  # Light deep head
  - hidden_layers: [128, 64, 32, 16]
    dropout_rates: [0.1, 0.1, 0.1, 0.1]

  # Test variant with mixed dropout
  - hidden_layers: [256, 64, 128]
    dropout_rates: [0.1, 0.3, 0.2]
