# ════════════════════════════════════════════════════════════════
# Fixed Parameters: Dataset, Architecture, and Runtime Settings
# ════════════════════════════════════════════════════════════════
global:
  N_threads: 8

data:
  root_path: /home/dlopez/Documents/Projects/JPAS_Domain_Adaptation/DATA/noise_jpas_v1/Train-Validate-Test

  load_JPAS_data:
    - name: all
      npy: JPAS_DATA_Aper_Cor_3_FLUX+NOISE.npy
      csv: JPAS_DATA_PROPERTIES.csv
      sample_percentage: 1.0

  load_DESI_data:
    - name: train
      npy: mock_3_train.npy
      csv: props_training.csv
      sample_percentage: 1.0
    - name: val
      npy: mock_3_validate.npy
      csv: props_validate.csv
      sample_percentage: 1.0
    - name: test
      npy: mock_3_test.npy
      csv: props_test.csv
      sample_percentage: 1.0

  random_seed_load: 0
  apply_masks: [unreliable, magic_numbers, negative_errors, nan_values, apply_additional_filters]
  mask_indices: [0, -2]
  magic_numbers: [-99, 99]
  i_band_sn_threshold: 0.0
  z_lim_QSO_cut: 2.2

  train_ratio_both: 0.7
  val_ratio_both: 0.15
  test_ratio_both: 0.15
  random_seed_split_both: 0

  train_ratio_only_DESI: 0.7
  val_ratio_only_DESI: 0.15
  test_ratio_only_DESI: 0.15
  random_seed_split_only_DESI: 0

  keys_xx: [OBS, ERR, MORPHTYPE_int]
  keys_yy: [SPECTYPE_int, TARGETID]
  normalize: true
  key_survey_training: JPAS_matched

models:
  path_load: /home/dlopez/Documents/Projects/JPAS_Domain_Adaptation/SAVED_models/11_wandb_no_DA/crimson-sweep-9

training:
  path_save: /home/dlopez/Documents/Projects/JPAS_Domain_Adaptation/SAVED_models/11_wandb_DA
  sampling_strategy: true_random
  freeze_downstream_model: True
  NN_epochs: 400
  seed_mode: deterministic
  seed: 0
  device: cuda
  batch_size_val: null
