# ════════════════════════════════════════════════════════════════════
# Global Configuration
# ════════════════════════════════════════════════════════════════════
global:
  N_threads: 1

# ════════════════════════════════════════════════════════════════════
# Data Configuration
# ════════════════════════════════════════════════════════════════════
data:
  cleaning_config: default_global_setup
  keys_xx: ["all_observations_normalized","MORPHTYPE_int"]
  keys_yy: ["SPECTYPE_int"]
  key_survey_training: JPAS_x_DESI_Raul

# ════════════════════════════════════════════════════════════════════
# Model Architecture
# ════════════════════════════════════════════════════════════════════
models:
  path_load: null

  encoder:
    hidden_layers: [64, 32, 16]
    dropout_rates: [0.02, 0.02, 0.02]
    output_dim: 8
    use_batchnorm: true

  downstream:
    hidden_layers: [16, 16]
    dropout_rates: [0.02, 0.02]
    use_batchnorm: true

# ════════════════════════════════════════════════════════════════════
# Training Configuration
# ════════════════════════════════════════════════════════════════════
training:
  path_save: default_global_setup
  default_overwrite : False

  sampling_strategy: true_random
  freeze_downstream_model: false
  l2_lambda: 0.002

  NN_epochs: 1024
  NN_batches_per_epoch: 2
  batch_size: 11051
  batch_size_val: null

  lr: 0.0005
  weight_decay: 0.001
  clip_grad_norm: 100.0

  seed_mode: deterministic
  seed: 137

  device: cuda
