# ════════════════════════════════════════════════════════════════════
# Global Configuration
# ════════════════════════════════════════════════════════════════════
global:
  N_threads: 1

# ════════════════════════════════════════════════════════════════════
# Data Configuration
# ════════════════════════════════════════════════════════════════════
data:
  # ── data_path ──
  data_paths: default_global_setup

  # ── clean_data_options ──
  dict_clean_data_options: default_global_setup
  
  # ── Train/val/test splits ──
  dict_split_data_options: default_global_setup

  # ── Input/output keys ──
  features_labels_options:
    define_dataset_loaders_keys: [DESI_only]
    keys_xx: [OBS, MORPHTYPE_int]
    keys_yy: [SPECTYPE_int]
    normalize: true
    normalization_source_key: DESI_only
    key_survey_training: DESI_only

# ════════════════════════════════════════════════════════════════════
# Model Architecture
# ════════════════════════════════════════════════════════════════════
models:
  path_load: null

  encoder:
    hidden_layers: [256, 128, 96]
    dropout_rates: [0.002, 0.002, 0.002]
    output_dim: 18

  downstream:
    hidden_layers: [128, 96]
    dropout_rates: [0.002, 0.002]

# ════════════════════════════════════════════════════════════════════
# Training Configuration
# ════════════════════════════════════════════════════════════════════
training:
  path_save: default_global_setup
  default_overwrite : False

  sampling_strategy: true_random
  freeze_downstream_model: false
  
  NN_epochs: 2048
  NN_batches_per_epoch: 4096
  batch_size: 24000
  batch_size_val: null

  lr: 0.008
  weight_decay: 0.00000001
  clip_grad_norm: 0.1

  seed_mode: deterministic
  seed: 42

  device: cuda
