# ════════════════════════════════════════════════════════════════════
# Global Configuration
# ════════════════════════════════════════════════════════════════════
global:
  N_threads: 1

# ════════════════════════════════════════════════════════════════════
# Data Configuration
# ════════════════════════════════════════════════════════════════════
data:
  cleaning_config: default_global_setup
  keys_xx: ["all_observations_normalized", "MORPHTYPE_int"]
  keys_yy: ["SPECTYPE_int"]
  key_survey_training: JPAS_x_DESI_Raul

# ════════════════════════════════════════════════════════════════════
# Model Architecture
# ════════════════════════════════════════════════════════════════════
models:
  path_load: 09_no_DA

  encoder:
    dropout_rates: [0.02, 0.02, 0.02]
    use_batchnorm: False

  downstream:
    dropout_rates: [0.02, 0.02]
    use_batchnorm: False

# ════════════════════════════════════════════════════════════════════
# Training Configuration
# ════════════════════════════════════════════════════════════════════
training:
  path_save: default_global_setup
  default_overwrite : False
  
  sampling_strategy: true_random
  freeze_downstream_model: True
  l2_lambda: 0.002
  
  NN_epochs: 1024
  NN_batches_per_epoch: 2
  batch_size: 11051
  batch_size_val: null

  lr: 0.0001
  weight_decay: 0.001
  clip_grad_norm: 0.00001

  seed_mode: deterministic
  seed: 137

  device: cuda
