# ════════════════════════════════════════════════════════════════════
# Global Configuration
# ════════════════════════════════════════════════════════════════════
global:
  N_threads: 1

# ════════════════════════════════════════════════════════════════════
# Data Configuration
# ════════════════════════════════════════════════════════════════════
data:
  # ── data_path ──
  data_paths: default_global_setup

  # ── clean_data_options ──
  dict_clean_data_options: default_global_setup
  
  # ── Train/val/test splits ──
  dict_split_data_options:
    train_ratio_both: 0.8
    val_ratio_both: 0.1
    test_ratio_both: 0.1
    random_seed_split_both: 0

    train_ratio_only_DESI: 0.8
    val_ratio_only_DESI: 0.1
    test_ratio_only_DESI: 0.1
    random_seed_split_only_DESI: 0

  # ── Input/output keys ──
  features_labels_options:
    keys_xx: [OBS, ERR, MORPHTYPE_int]
    keys_yy: [SPECTYPE_int, TARGETID]
    normalize: true
    key_survey_training: DESI_combined # JPAS_matched, DESI_matched, DESI_combined

# ════════════════════════════════════════════════════════════════════
# Model Architecture
# ════════════════════════════════════════════════════════════════════
models:
  path_load: null

  encoder:
    hidden_layers: [64, 64, 32, 16]
    dropout_rates: [0.02, 0.02, 0.02, 0.02]
    output_dim: 8

  downstream:
    hidden_layers: [32, 32]
    dropout_rates: [0.02, 0.02]

# ════════════════════════════════════════════════════════════════════
# Training Configuration
# ════════════════════════════════════════════════════════════════════
training:
  path_save: default_global_setup
  default_overwrite : False

  sampling_strategy: true_random
  freeze_downstream_model: false
  
  NN_epochs: 400
  NN_batches_per_epoch: 8192
  batch_size: 2048
  batch_size_val: null

  lr: 0.01
  weight_decay: 0.0001
  clip_grad_norm: 100.0

  seed_mode: deterministic
  seed: 0

  device: cuda
