global:
  N_threads: 8
data:
  data_paths: default_global_setup
  dict_clean_data_options: default_global_setup
  dict_split_data_options: default_global_setup
  features_labels_options:
    define_dataset_loaders_keys:
    - DESI_only
    - JPAS_matched
    keys_xx:
    - OBS
    - MORPHTYPE_int
    keys_yy:
    - SPECTYPE_int
    normalize: true
    normalization_source_key: DESI_only
    key_survey_training: JPAS_matched
models:
  path_load: wandb_no_DA/lemon-sweep-0
training:
  path_save: default_global_setup
  default_overwrite: false
  sampling_strategy: true_random
  freeze_downstream_model: true
  NN_epochs: 2048
  batch_size_val: null
  seed_mode: deterministic
  device: cuda
  NN_batches_per_epoch: 6973
  batch_size: 4588
  lr: 0.000999270953943512
  weight_decay: 0.0013037066406591487
  clip_grad_norm: 2.44725815643257
  seed: 726
