global:
  N_threads: 8
data:
  cleaning_config: default_global_setup
  keys_xx:
  - all_observations_normalized
  - MORPHTYPE_int
  keys_yy:
  - SPECTYPE_int
  key_survey_training: JPAS_x_DESI_Raul
models:
  path_load: wandb_no_DA/kind-sweep-46
  encoder:
    dropout_rates:
    - 0.001
    - 0.001
    - 0.001
    use_batchnorm: false
  downstream:
    dropout_rates:
    - 0.001
    - 0.001
    use_batchnorm: false
training:
  path_save: default_global_setup
  default_overwrite: false
  sampling_strategy: true_random
  freeze_downstream_model: true
  NN_epochs: 2500
  batch_size_val: 15597
  seed_mode: deterministic
  seed: 137
  device: cuda
  l2_lambda: 4.199420477983193e-07
  NN_batches_per_epoch: 7384
  batch_size: 15145
  lr: 0.07263880684298872
  weight_decay: 0.00016302271411089796
  clip_grad_norm: 5.358438367628115e-05
