# ════════════════════════════════════════════════════════════════
# Weights & Biases Sweep Configuration
# ════════════════════════════════════════════════════════════════

method: random                     # Sweep search strategy
name: "wandb_DA_my_sweep_1"      # Name of the sweep

# ════════════════════════════════════════════════════════════════
# Parameters to sweep over
# ════════════════════════════════════════════════════════════════
parameters:

  aux_config_path:
    value: aux_wandb_DA.yaml

  # ── Training Config ──
  NN_batches_per_epoch:
    distribution: int_uniform
    min: 512
    max: 8192

  batch_size:
    distribution: int_uniform
    min: 512
    max: 65536

  lr:
    distribution: log_uniform_values
    min: 0.0001
    max: 0.1

  weight_decay:
    distribution: log_uniform_values
    min: 0.00001
    max: 0.01

  clip_grad_norm:
    distribution: log_uniform_values
    min: 0.005
    max: 500.0

  seed:
    distribution: int_uniform
    min: 0
    max: 1000