# ════════════════════════════════════════════════════════════════
# Weights & Biases Sweep Configuration
# ════════════════════════════════════════════════════════════════

method: random                     # Sweep search strategy
name: "JPAS_DA"      # Name of the sweep

# ════════════════════════════════════════════════════════════════
# Parameters to sweep over
# ════════════════════════════════════════════════════════════════
parameters:

  aux_config_path:
    value: aux_wandb_DA.yaml

  # ── Training Config ──
  NN_batches_per_epoch:
    distribution: int_uniform
    min: 512
    max: 8192

  batch_size:
    distribution: int_uniform
    min: 64
    max: 8192

  lr:
    distribution: log_uniform_values
    min: 0.0001
    max: 0.1

  weight_decay:
    distribution: log_uniform_values
    min: 0.00001
    max: 0.01

  clip_grad_norm:
    distribution: uniform
    min: 0.1
    max: 100.0
