# ════════════════════════════════════════════════════════════════
# Weights & Biases Sweep Configuration
# ════════════════════════════════════════════════════════════════

method: random                           # Sweep search strategy
name: "wandb_supervised"                      # Name of the sweep

# ════════════════════════════════════════════════════════════════
# Parameters to sweep over
# ════════════════════════════════════════════════════════════════
parameters:

  aux_config_path:
    value: aux_wandb_supervised.yaml

  # ── Architecture Outputs ──
  output_dim:
    distribution: int_uniform
    min: 2
    max: 32

  # ── Training Config ──
  l2_lambda:
    distribution: log_uniform_values
    min: 0.0000000001
    max: 1.0
  
  NN_batches_per_epoch:
    distribution: int_uniform
    min: 2048
    max: 16384

  batch_size:
    distribution: int_uniform
    min: 1024
    max: 15597

  lr:
    distribution: log_uniform_values
    min: 0.0001
    max: 0.1

  weight_decay:
    distribution: log_uniform_values
    min: 0.000001
    max: 0.1

  clip_grad_norm:
    distribution: log_uniform_values
    min: 0.0001
    max: 100.0

  # ── Architecture Selector Indices ──
  encoder_id:
    values: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

  downstream_id:
    values: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

